# Generated by Django 5.0.3 on 2025-03-11 22:29

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('vip_author', django.db.models.manager.Manager()),
            ],
        ),
    ]
