# Generated by Django 5.0.3 on 2024-03-07 13:06

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('Maths', 'Maths'), ('Physics', 'Physics')], default='Bangla', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='tuition/images'),
        ),
    ]
