# Generated by Django 5.0.3 on 2024-03-12 05:45

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0007_post_class_in_post_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English')], default='Bangla', max_length=100),
        ),
    ]
