# Generated by Django 5.0.3 on 2024-04-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0009_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subjects',
        ),
    ]
