# Generated by Django 5.0.3 on 2024-04-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0010_remove_post_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
