# Generated by Django 5.0.3 on 2024-04-08 06:43

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0012_post_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Urdu', 'Urdu'), ('Arabic', 'Arabic')], max_length=100),
        ),
    ]
