# Generated by Django 5.0.3 on 2024-04-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0013_alter_post_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='medium',
        ),
    ]
