# Generated by Django 5.0.3 on 2024-05-13 11:41

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0015_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Urdu', 'Urdu'), ('Arabic', 'Arabic')], default='Bangla', max_length=100),
            preserve_default=False,
        ),
    ]
