# Generated by Django 5.0.3 on 2024-05-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0017_alter_post_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_in',
            name='section',
            field=models.CharField(default='A', max_length=5),
        ),
    ]
